CREATE TABLE test.ORDERS
(
    id           INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date         TIMESTAMP DEFAULT now() not null,
    customer_id  INTEGER                 NOT NULL,
    product_name VARCHAR(255)            NOT NULL,
    amount       FLOAT                   NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES test.CUSTOMERS (id) ON DELETE CASCADE
);

INSERT INTO test.ORDERS (date, customer_id, product_name, amount)
VALUES ('2023-03-01 12:45:00', 1, 'Часы', 2999),
       ('2023-03-01 13:32:00', 2, 'Телефон', 20500),
       ('2023-03-01 18:48:00', 3, 'Книга', 400),
       ('2023-03-02 15:12:00', 1, 'Кофе', 699.99),
       ('2023-03-02 16:45:00', 4, 'Клавиатура', 2099),
       ('2023-03-03 10:45:00', 5, 'Набор ручек', 299),
       ('2023-03-03 11:45:00', 6, 'Рубашка', 3000),
       ('2023-03-03 19:40:00', 1, 'Ботинки', 4999);
