CREATE SCHEMA test;

CREATE TABLE test.CUSTOMERS
(
    id           INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name         VARCHAR(255)       NOT NULL,
    surname      VARCHAR(255)       NOT NULL,
    age          int                NOT NULL,
    phone_number VARCHAR(50) UNIQUE NOT NULL
);

INSERT INTO test.CUSTOMERS (name, surname, age, phone_number)
VALUES ('Алексей', 'Петров', 26, '8-654-6541-9871'),
       ('Аня', 'Петров', 24, '5-4325-4657-4563'),
       ('Витя', 'Ромашкин', 56, '6-465-4978-4321'),
       ('Евгения', 'Жмурикова', 35, '5-2544-654-987'),
       ('Роман', 'Козюлин', 55, '3-654-654-2451'),
       ('Оля', 'Резанцова', 18, '5-654-4571-987');
